name: Step 0 # 演習を開始

on:
  push:
    branches:
      - main

permissions:
  contents: write # READMEを更新
  actions: write # ワークフローの有効化/無効化
  issues: write # Issueの作成とコメント

env:
  STEP_1_FILE: ".github/steps/1-create-a-branch.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: 演習を開始
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.8.1
    with:
      exercise-title: "GitHub 入門"
      intro-message: "GitHubが初めての方は、開発者仲間が ___**Issue**___ を使って作業を整理し、コラボレーションしていることに気づくでしょう。私たちも同じようにやります！それはまた別のレッスンですが、今日はGitHubの基本を紹介します。"

  post_next_step_content:
    name: 次のステップの内容を投稿
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          ref: main

      - name: コメントを作成 - ステップ内容を追加
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}

      - name: コメントを作成 - 進捗を監視中
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/step-feedback/watching-for-progress.md

      - name: 現在のワークフローを無効化し、次を有効化
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
