name: Step 1 # ブランチを作成する

# 学習者がステップ1のタスクを完了したか確認します。
# - ユーザーが新しいブランチ 'my-first-branch' を作成したときにトリガーされます。
# - ブランチ名が 'my-first-branch' であることを確認します。
# - すべてのチェックに合格すると、再実行されないようにワークフローが無効化されます。その結果、ワークフローのステータスバッジが緑色に変わります。

on:
  push:
    branches:
      - "my-first-branch"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-commit-a-file.md"

jobs:
  find_exercise:
    name: 演習のIssueを検索
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0
    with:
      issue-title-text: "演習: "

  post_next_step_content:
    name: 次のステップの内容を投稿
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: コメントを作成 - ステップ完了
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 2

      - name: コメントを作成 - ステップ内容を追加
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_2_FILE }}

      - name: コメントを作成 - 進捗を監視中
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/step-feedback/watching-for-progress.md

      - name: 現在のワークフローを無効化し、次を有効化
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 2"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
